### PR TITLE
feat: treat all FIL+ deals as publicly retrievable

### PR DESCRIPTION
**Pull request by bajtos**
After the FIL+ LDN program was superseded by v5 Allocators, there is no longer any easy way to compile a list of all clients with datacap allowance for open public data (data that should be publicly retrievable).

I discussed this problem with @patrickwoodhead and FIDL, and we decided to treat all verified (FIL+) deals as publicly retrievable.

This is a short-term solution. We will improve it later when better tooling is available to detect which clients are storing open public data.

Links:
- https://github.com/space-meridian/roadmap/issues/115

### CODE REVIEW

**Comment by bajtos** [comment]
@juliangruber what's your take on removing or keeping the following files that are no longer used?

- [scripts/fetch-open-data-clients.js](https://github.com/filecoin-station/fil-deal-ingester/blob/9f517206639c97317b579969aea543d76fd2cf90/scripts/fetch-open-data-clients.js)
- [scripts/ldn-notaries-snapshot.js](https://github.com/filecoin-station/fil-deal-ingester/blob/9f517206639c97317b579969aea543d76fd2cf90/scripts/ldn-notaries-snapshot.js)
- [generated/open-data-clients.csv](https://github.com/filecoin-station/fil-deal-ingester/blob/9f517206639c97317b579969aea543d76fd2cf90/generated/open-data-clients.csv)

**Comment by bajtos** [comment]
ok, I removed those files. It's easy to bring them back from the git history if we ever need them.

**Comment by bajtos** [comment]
@juliangruber hindsight please 🙏🏻

**Review by juliangruber — COMMENTED** [review]
lgtm!

**Pull request merged**
