### PR TITLE
feat: add support for Pathway Allocators (v5)

### PR DESCRIPTION
**Pull request by bajtos**
- **feat: update LDN clients**
- **feat: add support for Pathway Allocators (v5)**

Also add https://github.com/fidlabs/Open-Data-Pathway as the first known allocator that requires stored data to be publicly retrievable.

Links:
- https://github.com/space-meridian/roadmap/issues/115

### CODE REVIEW

**Comment by bajtos** [comment]
The second commit added the following three new clients that would not be picked up before my changes:

- f02011705
- f03123037
- f03139621

See https://github.com/filecoin-station/fil-deal-ingester/pull/15/commits/d59ff9ece7503efe83fcef517ff2ea9e3f835b5e#diff-f473a777bc0662fb256384ee2c76d96e36706572292e63ccfe834ab5ee7b324f

**Comment by bajtos** [comment]
Hmm, my intention was to push the first commit directly to the main branch and then keep only the second commit in this pull request. 🙈

**Review by juliangruber — APPROVED** [review]
all lgtm 👏

**Comment by bajtos** [comment]
> > Hmm, my intention was to push the first commit directly to the main branch and then keep only the second commit in this pull request. 🙈
> 
> if you push the first commit to main then this PR will only contain the 2nd :) should be straight forward with git cherry-pick

Yes, that's what I though, but it didn't work out.

Screenshot 2024-06-20 at 08 51 27
Screenshot 2024-06-20 at 08 51 31

**Pull request merged**
